mode: daemonset

daemonset:
  securityContext:
    runAsUser: 0
  extraVolumes:
    - name: varlog
      hostPath:
        path: /var/log
  extraVolumeMounts:
    - name: varlog
      mountPath: /var/log
