name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi-vcpkg"
          configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"
          buildPreset: "ninja-multi-vcpkg"
          buildPresetAdditionalArgs: "['--config Release']"

      - name: Build
        run: cmake --build build -j

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: build/cpp_quant
          if-no-files-found: error
