name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Setup anew
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "${{ matrix.vcpkgCommitId }}"

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_FEATURE_FLAGS=manifests

      - name: Build
        run: cmake --build build -j

      - name: Run binary (smoke test)
        run: |
          ./build/cpp-quant --help || true
