name: build-and-deploy
on:
  push: { branches: ["main"] }

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REG: registry.digitalocean.com/quant-registry
      IMAGE: cpp-quant
      TAG: ${{ github.sha }}
      DO_CLUSTER: quant-dev
      K8S_NS: quant
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login

      - name: Build & push (linux/amd64) with cache
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $REG/$IMAGE:$TAG -t $REG/$IMAGE:latest \
            --cache-to=type=registry,ref=$REG/build-cache:$IMAGE,mode=max \
            --cache-from=type=registry,ref=$REG/build-cache:$IMAGE \
            --push .

      - name: Kubeconfig
        run: doctl kubernetes cluster kubeconfig save "$DO_CLUSTER"

      - name: Rollout new image
        run: |
          kubectl -n $K8S_NS set image deploy/$IMAGE app=$REG/$IMAGE:$TAG
          kubectl -n $K8S_NS rollout status deploy/$IMAGE
