name: deploy
on:
  push: { branches: ["main"] }

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: staging
    env:
      ROOT_DIR: engine
      IMAGE: quant-engine
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login

      - name: Build & push (linux/amd64) with cache
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $CONTAINER_REGISTRY/$IMAGE:${{ github.sha }} -t "$CONTAINER_REGISTRY/$IMAGE:latest" \
            --push ${ROOT_DIR}

      # - name: Prune old tags
      #   run: ./scripts/prune-docr-tags.sh

      - name: Kubeconfig
        run: doctl kubernetes cluster kubeconfig save "$DO_CLUSTER"

      - name: Rollout new image
        run: |
          kubectl -n $K8S_NS set image deploy/$IMAGE app=$CONTAINER_REGISTRY/$IMAGE:$TAG
          kubectl -n $K8S_NS rollout status deploy/$IMAGE
