name: deploy
on:
  push: { branches: ["main"] }

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REG: registry.digitalocean.com/quant-registry
      IMAGE: cpp-quant
      TAG: ${{ github.sha }}
      DO_CLUSTER: quant-dev
      K8S_NS: quant
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login

      - name: Build & push (linux/amd64) with cache
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $REG/$IMAGE:${{ github.sha }} -t $REG/$IMAGE:latest \
            --push .

      - name: Prune old tags
        run: |
          KEEP=5
          TAGS=$(doctl registry repository list-tags cpp-quant --format Tag,UpdatedAt --no-header \
            | sort -k2 -r | awk '{print $1}')
          n=0
          for T in $TAGS; do
            n=$((n+1))
            [ $n -le $KEEP ] && continue
            doctl registry repository delete-tag cpp-quant "$T" --force
          done

      - name: Kubeconfig
        env:
          DO_CLUSTER: quant-dev
        run: doctl kubernetes cluster kubeconfig save "$DO_CLUSTER"

      - name: Rollout new image
        run: |
          kubectl -n $K8S_NS set image deploy/$IMAGE app=$REG/$IMAGE:$TAG
          kubectl -n $K8S_NS rollout status deploy/$IMAGE
