name: engine-build

on:
  push:
    branches: ["main"]
    paths:
      - "engine/**"
      - ".github/workflows/engine/**"
  pull_request:
    branches: ["main"]
    paths:
      - "engine/**"
      - ".github/workflows/engine/**"

jobs:
  build:
    defaults:
      run:
        working-directory: engine
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build
    steps:
      - uses: actions/checkout@v5
      - uses: lukka/get-cmake@latest
      - uses: conan-io/setup-conan@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build/test
        run: make test

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: quant_engine
          path: ./engine/build/Release/src/quant_engine
          if-no-files-found: error

      - name: Archive tests
        uses: actions/upload-artifact@v4
        with:
          name: quant_engine
          path: ./engine/build/Release/ctest-junit.xml
          if-no-files-found: error
