name: web-ui-deploy
on:
  push:
    branches: ["main"]
    paths:
      - "web-ui/**"
      - ".github/workflows/web_ui**"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: staging
    env:
      CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
      ROOT_DIR: web-ui
      REPO: cpp-quant
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set tags
        id: vars
        run: |
          echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "UI_TAG=ui-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login

      - name: Build & push web-ui (linux/amd64)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $CONTAINER_REGISTRY/$REPO:${{ steps.vars.outputs.UI_TAG }} \
            -t "$CONTAINER_REGISTRY/$REPO:ui-latest" \
            --push "$ROOT_DIR"

      # Optional: prune old UI tags to avoid DOCR quota
      # - name: Prune old DOCR tags
      #   run: ./scripts/prune-docr-tags.sh || true

      - name: Fetch kubeconfig
        run: doctl kubernetes cluster kubeconfig save "$DO_CLUSTER"

      - name: Rollout web-ui
        run: |
          kubectl -n $K8S_NS set image deploy/web-ui web-ui=$CONTAINER_REGISTRY/$REPO:${{ steps.vars.outputs.UI_TAG }}
          kubectl -n $K8S_NS rollout status deploy/web-ui
